//! Integration tests against committed DAR corpus.
//!
//! `test.dar` is generated by a Python script from the format spec, independent
//! from the Rust parser. Known contents allow exact byte-level assertions.
//!
//! Archive contents:
//!   boot/mbr.bin  — 512 bytes (bytes 0..=255 repeated twice)
//!   etc/hostname  — b"corpus-host\n"
//!   data/pattern  — 4096 bytes (bytes 0..=255 repeated 16 times)

use std::io::Cursor;
use std::path::Path;
use dar::DarReader;

const DATA_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/data");

fn open() -> DarReader<Cursor<Vec<u8>>> {
    let path = format!("{DATA_DIR}/test.dar");
    let data = std::fs::read(Path::new(&path))
        .unwrap_or_else(|e| panic!("read test.dar: {e}"));
    DarReader::open(Cursor::new(data))
        .unwrap_or_else(|e| panic!("DarReader::open test.dar: {e}"))
}

// ── open ─────────────────────────────────────────────────────────────────────

#[test]
fn corpus_opens() {
    let _ = open();
}

// ── entries ───────────────────────────────────────────────────────────────────

#[test]
fn corpus_has_three_entries() {
    assert_eq!(open().entries().len(), 3);
}

#[test]
fn corpus_entry_paths() {
    let r = open();
    let entries = r.entries();
    let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();
    assert!(paths.contains(&"boot/mbr.bin"), "must contain boot/mbr.bin");
    assert!(paths.contains(&"etc/hostname"),  "must contain etc/hostname");
    assert!(paths.contains(&"data/pattern"),  "must contain data/pattern");
}

#[test]
fn corpus_entry_sizes() {
    let r = open();
    let entries = r.entries();
    let by_name = |n: &str| entries.iter().find(|e| e.path == n).unwrap().size;
    assert_eq!(by_name("boot/mbr.bin"),  512,  "boot/mbr.bin must be 512 bytes");
    assert_eq!(by_name("etc/hostname"),  12,   "etc/hostname must be 12 bytes");
    assert_eq!(by_name("data/pattern"),  4096, "data/pattern must be 4096 bytes");
}

// ── extract ───────────────────────────────────────────────────────────────────

#[test]
fn extract_hostname() {
    let mut r = open();
    let data = r.extract("etc/hostname").expect("extract etc/hostname");
    assert_eq!(data, b"corpus-host\n");
}

#[test]
fn extract_mbr_bin_content() {
    let mut r = open();
    let data = r.extract("boot/mbr.bin").expect("extract boot/mbr.bin");
    assert_eq!(data.len(), 512);
    // bytes(range(256)) * 2
    let expected: Vec<u8> = (0u8..=255).chain(0u8..=255).collect();
    assert_eq!(data, expected);
}

#[test]
fn extract_pattern_content() {
    let mut r = open();
    let data = r.extract("data/pattern").expect("extract data/pattern");
    assert_eq!(data.len(), 4096);
    let expected: Vec<u8> = std::iter::repeat(0u8..=255u8)
        .flat_map(|r| r)
        .take(4096)
        .collect();
    assert_eq!(data, expected);
}

#[test]
fn extract_all_entries_succeed() {
    let mut r = open();
    for entry in r.entries() {
        r.extract(&entry.path)
            .unwrap_or_else(|e| panic!("extract({}) failed: {e}", entry.path));
    }
}

// ── error cases ───────────────────────────────────────────────────────────────

#[test]
fn extract_missing_path_returns_err() {
    let mut r = open();
    assert!(
        r.extract("no/such/file").is_err(),
        "extracting non-existent path must return Err"
    );
}

#[test]
fn open_empty_returns_err() {
    let result = DarReader::open(Cursor::new(vec![]));
    assert!(result.is_err(), "opening empty bytes must return Err");
}

#[test]
fn open_truncated_returns_err() {
    let result = DarReader::open(Cursor::new(b"DAR\x00\x01\x00\x00\x00".to_vec()));
    assert!(result.is_err(), "truncated archive must return Err");
}

#[test]
fn open_wrong_magic_returns_err() {
    let result = DarReader::open(Cursor::new(b"XXXX\x01\x00\x00\x00\x00\x00\x00\x00".to_vec()));
    assert!(result.is_err(), "wrong magic must return Err");
}
